return {
["rows"] = {{
["id"] = 1,
["pos"] = 1,
["type"] = 1,
["identity"] = 1,
["kickOffPos"] = {0,0},
["minPos"] = {-2.1,0},
["maxPos"] = {7.14,0},
},{
["id"] = 2,
["pos"] = 2,
["type"] = 1,
["identity"] = 2,
["kickOffPos"] = {-3,-1.4},
["minPos"] = {-4.56,-1.4},
["maxPos"] = {4.24,-1.4},
},{
["id"] = 3,
["pos"] = 3,
["type"] = 1,
["identity"] = 2,
["kickOffPos"] = {-3,1.4},
["minPos"] = {-4.56,1.4},
["maxPos"] = {4.24,1.4},
},{
["id"] = 4,
["pos"] = 4,
["type"] = 1,
["identity"] = 2,
["kickOffPos"] = {-5,0},
["minPos"] = {-5.26,0},
["maxPos"] = {1,0},
},{
["id"] = 5,
["pos"] = 5,
["type"] = 1,
["identity"] = 3,
["kickOffPos"] = {-7.5,1.4},
["minPos"] = {-7.82,1.4},
["maxPos"] = {-2.2,1.4},
},{
["id"] = 6,
["pos"] = 6,
["type"] = 1,
["identity"] = 3,
["kickOffPos"] = {-7.5,-1.4},
["minPos"] = {-7.82,-1.4},
["maxPos"] = {-2.2,-1.4},
},{
["id"] = 7,
["pos"] = 7,
["type"] = 1,
["identity"] = 4,
["kickOffPos"] = {-9.5,0},
["minPos"] = {-9.5,0},
["maxPos"] = {-9.5,0},
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
},{
["id"] = 0,
["pos"] = 0,
["type"] = 0,
["identity"] = 0,
}},
}