/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.idleafk.Formation');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idleafk.Formation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idleafk.Formation.repeatedFields_, null);
};
goog.inherits(proto.idleafk.Formation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.idleafk.Formation.displayName = 'proto.idleafk.Formation';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idleafk.Formation.repeatedFields_ = [5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idleafk.Formation.prototype.toObject = function(opt_includeInstance) {
  return proto.idleafk.Formation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idleafk.Formation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idleafk.Formation.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    pos: jspb.Message.getFieldWithDefault(msg, 2, 0),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    identity: jspb.Message.getFieldWithDefault(msg, 4, 0),
    kickoffposList: jspb.Message.getRepeatedFloatingPointField(msg, 5),
    minposList: jspb.Message.getRepeatedFloatingPointField(msg, 6),
    maxposList: jspb.Message.getRepeatedFloatingPointField(msg, 7)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idleafk.Formation}
 */
proto.idleafk.Formation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idleafk.Formation;
  return proto.idleafk.Formation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idleafk.Formation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idleafk.Formation}
 */
proto.idleafk.Formation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setPos(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setIdentity(value);
      break;
    case 5:
      var value = /** @type {!Array.<number>} */ (reader.readPackedFloat());
      msg.setKickoffposList(value);
      break;
    case 6:
      var value = /** @type {!Array.<number>} */ (reader.readPackedFloat());
      msg.setMinposList(value);
      break;
    case 7:
      var value = /** @type {!Array.<number>} */ (reader.readPackedFloat());
      msg.setMaxposList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idleafk.Formation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idleafk.Formation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idleafk.Formation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idleafk.Formation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeSint32(
      1,
      f
    );
  }
  f = message.getPos();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0) {
    writer.writeSint32(
      3,
      f
    );
  }
  f = message.getIdentity();
  if (f !== 0) {
    writer.writeSint32(
      4,
      f
    );
  }
  f = message.getKickoffposList();
  if (f.length > 0) {
    writer.writePackedFloat(
      5,
      f
    );
  }
  f = message.getMinposList();
  if (f.length > 0) {
    writer.writePackedFloat(
      6,
      f
    );
  }
  f = message.getMaxposList();
  if (f.length > 0) {
    writer.writePackedFloat(
      7,
      f
    );
  }
};


/**
 * optional sint32 id = 1;
 * @return {number}
 */
proto.idleafk.Formation.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.idleafk.Formation.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional sint32 pos = 2;
 * @return {number}
 */
proto.idleafk.Formation.prototype.getPos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.idleafk.Formation.prototype.setPos = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional sint32 type = 3;
 * @return {number}
 */
proto.idleafk.Formation.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.idleafk.Formation.prototype.setType = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional sint32 identity = 4;
 * @return {number}
 */
proto.idleafk.Formation.prototype.getIdentity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.idleafk.Formation.prototype.setIdentity = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated float kickOffPos = 5;
 * @return {!Array.<number>}
 */
proto.idleafk.Formation.prototype.getKickoffposList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 5));
};


/** @param {!Array.<number>} value */
proto.idleafk.Formation.prototype.setKickoffposList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.idleafk.Formation.prototype.addKickoffpos = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.idleafk.Formation.prototype.clearKickoffposList = function() {
  this.setKickoffposList([]);
};


/**
 * repeated float minPos = 6;
 * @return {!Array.<number>}
 */
proto.idleafk.Formation.prototype.getMinposList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 6));
};


/** @param {!Array.<number>} value */
proto.idleafk.Formation.prototype.setMinposList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.idleafk.Formation.prototype.addMinpos = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


proto.idleafk.Formation.prototype.clearMinposList = function() {
  this.setMinposList([]);
};


/**
 * repeated float maxPos = 7;
 * @return {!Array.<number>}
 */
proto.idleafk.Formation.prototype.getMaxposList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 7));
};


/** @param {!Array.<number>} value */
proto.idleafk.Formation.prototype.setMaxposList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.idleafk.Formation.prototype.addMaxpos = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.idleafk.Formation.prototype.clearMaxposList = function() {
  this.setMaxposList([]);
};


