/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.idleafk.TotalData');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.idleafk.ItemInfo');

goog.forwardDeclare('proto.idleafk.Identity');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idleafk.TotalData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idleafk.TotalData.repeatedFields_, null);
};
goog.inherits(proto.idleafk.TotalData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.idleafk.TotalData.displayName = 'proto.idleafk.TotalData';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idleafk.TotalData.repeatedFields_ = [2,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idleafk.TotalData.prototype.toObject = function(opt_includeInstance) {
  return proto.idleafk.TotalData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idleafk.TotalData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idleafk.TotalData.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    coursesList: jspb.Message.getRepeatedField(msg, 2),
    iden: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dresscost: (f = msg.getDresscost()) && proto.idleafk.ItemInfo.toObject(includeInstance, f),
    drinkList: jspb.Message.toObjectList(msg.getDrinkList(),
    proto.idleafk.ItemInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idleafk.TotalData}
 */
proto.idleafk.TotalData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idleafk.TotalData;
  return proto.idleafk.TotalData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idleafk.TotalData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idleafk.TotalData}
 */
proto.idleafk.TotalData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addCourses(value);
      break;
    case 3:
      var value = /** @type {!proto.idleafk.Identity} */ (reader.readEnum());
      msg.setIden(value);
      break;
    case 4:
      var value = new proto.idleafk.ItemInfo;
      reader.readMessage(value,proto.idleafk.ItemInfo.deserializeBinaryFromReader);
      msg.setDresscost(value);
      break;
    case 5:
      var value = new proto.idleafk.ItemInfo;
      reader.readMessage(value,proto.idleafk.ItemInfo.deserializeBinaryFromReader);
      msg.addDrink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idleafk.TotalData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idleafk.TotalData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idleafk.TotalData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idleafk.TotalData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCoursesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getIden();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDresscost();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.idleafk.ItemInfo.serializeBinaryToWriter
    );
  }
  f = message.getDrinkList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.idleafk.ItemInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.idleafk.TotalData.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.idleafk.TotalData.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string courses = 2;
 * @return {!Array.<string>}
 */
proto.idleafk.TotalData.prototype.getCoursesList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array.<string>} value */
proto.idleafk.TotalData.prototype.setCoursesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.idleafk.TotalData.prototype.addCourses = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.idleafk.TotalData.prototype.clearCoursesList = function() {
  this.setCoursesList([]);
};


/**
 * optional Identity iden = 3;
 * @return {!proto.idleafk.Identity}
 */
proto.idleafk.TotalData.prototype.getIden = function() {
  return /** @type {!proto.idleafk.Identity} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.idleafk.Identity} value */
proto.idleafk.TotalData.prototype.setIden = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional ItemInfo dressCost = 4;
 * @return {?proto.idleafk.ItemInfo}
 */
proto.idleafk.TotalData.prototype.getDresscost = function() {
  return /** @type{?proto.idleafk.ItemInfo} */ (
    jspb.Message.getWrapperField(this, proto.idleafk.ItemInfo, 4));
};


/** @param {?proto.idleafk.ItemInfo|undefined} value */
proto.idleafk.TotalData.prototype.setDresscost = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.idleafk.TotalData.prototype.clearDresscost = function() {
  this.setDresscost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.idleafk.TotalData.prototype.hasDresscost = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated ItemInfo drink = 5;
 * @return {!Array.<!proto.idleafk.ItemInfo>}
 */
proto.idleafk.TotalData.prototype.getDrinkList = function() {
  return /** @type{!Array.<!proto.idleafk.ItemInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.idleafk.ItemInfo, 5));
};


/** @param {!Array.<!proto.idleafk.ItemInfo>} value */
proto.idleafk.TotalData.prototype.setDrinkList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.idleafk.ItemInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.idleafk.ItemInfo}
 */
proto.idleafk.TotalData.prototype.addDrink = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.idleafk.ItemInfo, opt_index);
};


proto.idleafk.TotalData.prototype.clearDrinkList = function() {
  this.setDrinkList([]);
};


